import json
from utils.llm import llm


def rank_solutions(task, results):

    solutions_text = ""

    for idx, result in enumerate(results):

        solutions_text += f"""

AGENT {idx + 1}
NAME: {result['agent'].name}

SOLUTION:
{result['solution']}

====================================
"""

    judge_prompt = f"""
You are an expert evaluator.

TASK:
{task}

Below are multiple solutions generated by different AI agents.

Rank all solutions from best to worst.

Evaluate using:

1. Novelty
2. Feasibility
3. Completeness
4. Clarity

Return ONLY valid JSON.

Example:

[
    {{
        "agent_name": "Agent_1",
        "score": 37,
        "rank": 1
    }},
    {{
        "agent_name": "Agent_2",
        "score": 33,
        "rank": 2
    }}
]

SOLUTIONS:

{solutions_text}
"""

    response = llm.invoke(judge_prompt)

    content = response.content.strip()

    try:

        start = content.find("[")
        end = content.rfind("]") + 1

        json_text = content[start:end]

        return json.loads(json_text)

    except Exception:

        return []